#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Tagview.Resource", IsApplication=true)]

namespace Tagview
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int sort_options_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_add_white_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_delete_white_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_edit_white_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_expand_less_white_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_expand_more_white_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_folder_white_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_photo_white_24dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070014
			public const int ListItemImage = 2131165204;
			
			// aapt resource value: 0x7f070004
			public const int ListItemText = 2131165188;
			
			// aapt resource value: 0x7f070025
			public const int addDirectory_btn = 2131165221;
			
			// aapt resource value: 0x7f070002
			public const int add_child_btn = 2131165186;
			
			// aapt resource value: 0x7f070013
			public const int cancel_btn = 2131165203;
			
			// aapt resource value: 0x7f070019
			public const int categories = 2131165209;
			
			// aapt resource value: 0x7f070003
			public const int children_lvw = 2131165187;
			
			// aapt resource value: 0x7f070028
			public const int clear_database_btn = 2131165224;
			
			// aapt resource value: 0x7f070007
			public const int delete_child_btn = 2131165191;
			
			// aapt resource value: 0x7f070026
			public const int directory_lvw = 2131165222;
			
			// aapt resource value: 0x7f070006
			public const int edit_child_btn = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int enabled_swt = 2131165189;
			
			// aapt resource value: 0x7f070010
			public const int file_lvw = 2131165200;
			
			// aapt resource value: 0x7f07001a
			public const int filters = 2131165210;
			
			// aapt resource value: 0x7f07001f
			public const int fragment_container = 2131165215;
			
			// aapt resource value: 0x7f070016
			public const int imageview_main = 2131165206;
			
			// aapt resource value: 0x7f07000e
			public const int includeChildren_swt = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int includeChildren_txt = 2131165197;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070011
			public const int linearLayout3 = 2131165201;
			
			// aapt resource value: 0x7f070009
			public const int linearLayout4 = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int linearLayout5 = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int parent_spn = 2131165195;
			
			// aapt resource value: 0x7f07001e
			public const int preferences = 2131165214;
			
			// aapt resource value: 0x7f070029
			public const int reset_settings_btn = 2131165225;
			
			// aapt resource value: 0x7f070018
			public const int restart = 2131165208;
			
			// aapt resource value: 0x7f070017
			public const int resume = 2131165207;
			
			// aapt resource value: 0x7f070021
			public const int reverse_chb = 2131165217;
			
			// aapt resource value: 0x7f070012
			public const int select_btn = 2131165202;
			
			// aapt resource value: 0x7f07001b
			public const int sequences = 2131165211;
			
			// aapt resource value: 0x7f07001d
			public const int settings = 2131165213;
			
			// aapt resource value: 0x7f070023
			public const int slideShowPeriodSecs_txt = 2131165219;
			
			// aapt resource value: 0x7f070020
			public const int sort_options_spn = 2131165216;
			
			// aapt resource value: 0x7f07001c
			public const int tag = 2131165212;
			
			// aapt resource value: 0x7f070027
			public const int tag_txt = 2131165223;
			
			// aapt resource value: 0x7f070015
			public const int text1 = 2131165205;
			
			// aapt resource value: 0x7f07000a
			public const int textView1 = 2131165194;
			
			// aapt resource value: 0x7f07000f
			public const int textView2 = 2131165199;
			
			// aapt resource value: 0x7f070022
			public const int timingDown_btn = 2131165218;
			
			// aapt resource value: 0x7f070024
			public const int timingUp_btn = 2131165220;
			
			// aapt resource value: 0x7f070001
			public const int title_tvw = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int title_txt = 2131165192;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DataList = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DataListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FileDialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FileListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int large_spinner = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int medium_spinner = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int menu = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int preferences = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int sequence = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int settings = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int SelectDirectory = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int SelectFile = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int buttonBorderProportion = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int buttonSurroundTint = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int categoryListAnimationPeriod = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int categoryListMarginProportion = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int categoryListProportion = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int categorySelectionAnimationPeriod = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int currentDirectory = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int currentFile = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int currentIndex = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int currentSequenceId = 2131034127;
			
			// aapt resource value: 0x7f05000a
			public const int maxCacheEntries = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int radiusProportion = 2131034115;
			
			// aapt resource value: 0x7f05000b
			public const int version = 2131034123;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
